apiVersion: v1
kind: Service
metadata:
  name: quota-limitrange-admission-manager
  labels:
    app: cdp-limitrange-customizer
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: cdp-limitrange-customizer
